apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: monitor
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      name: monitor
      namespace: monitor
      labels:
        app: monitor
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          resources:
            limits:
              memory: 500Mi
              cpu: 100m
          ports:
            - name: prometheus
              protocol: TCP
              containerPort: 9090
        - name: grafana
          image: grafana/grafana
          resources:
            limits:
              memory: 500Mi
              cpu: 100m
          ports:
            - name: grafana
              protocol: TCP
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: monitor
spec:
  selector:
    app: monitor
  type: NodePort
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
